

export const DISPLAY_ALERT = "DISPLAY_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

export const LOGOUT_USER = "LOGOUT_USER";
export const HANDLE_CHANGE = "HANDLE_CHANGE";

export const CLEAR_VALUES = "CLEAR_VALUES";

export const CREATE_TASK_BEGIN = "CREATE_TASK_BEGIN";
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const CREATE_TASK_ERROR = "CREATE_TASK_ERROR";

export const GET_TASK_BEGIN = "GET_TASK_BEGIN";
export const GET_TASK_SUCCESS = "GET_TASK_SUCCESS";

export const SET_EDIT_TASK = "EDIT_TASK";

export const DELETE_TASK_BEGIN = "DELETE_TASK_BEGIN";

export const EDIT_TASK_BEGIN = "EDIT_TASK_BEGIN";
export const EDIT_TASK_SUCCESS = "EDIT_TASK_SUCCESS";
export const EDIT_TASK_ERROR = "EDIT_TASK_ERROR";

export const SHOW_STAT_BEGIN = "SHOW_STAT_BEGIN";
export const SHOW_STAT_SUCCESS = "SHOW_STAT_SUCCESS";
export const SHOW_STAT_ERROR = "SHOW_STAT_ERROR";

export const CLEAR_FILTERS = "CLEAR_FILTERS";

export const CHANGE_PAGE = "CHANGE_PAGE";


